[package]

name = "spinning-square"
version = "0.1.0"
authors = [
    "TyOverby <ty@pre-alpha.com>",
    "Nikita Pekin <contact@nikitapek.in>"
]

[[bin]]
name = "spinning-square"

[dependencies]
piston = "0.46.0"
piston2d-graphics = "0.32.0"
pistoncore-glutin_window = "0.59.0"
piston2d-opengl_graphics = "0.65.0"
