[package]
authors = ["Sven Nilsen <bvssvni@gmail.com>"]
name = "sudoku"
version = "0.1.0"
[[bin]]
name = "sudoku"

[dependencies]
piston = "*"
piston2d-graphics = "*"
piston2d-opengl_graphics = "*"
pistoncore-glutin_window = "*"
