[package]
authors = ["Sven Nilsen <bvssvni@gmail.com>"]
name = "sudoku"
version = "0.1.0"
[[bin]]
name = "sudoku"

[dependencies]
piston = "0.52.0"
piston2d-graphics = "0.37.0"
pistoncore-glutin_window = "0.66.0"
piston2d-opengl_graphics = "0.74.0"
